Ext.define('WineBook.view.util.popups.About', {
    extend: 'Ext.Panel',
    xtype: 'aboutpanel',
    id:  'about-id',

    config: {
        title: 'About',
        scrollable: true,
        floating: true,
        centered: true,
        hideOnMaskTap: true,
        modal: true,
        showAnimation: {type: 'slide', direction: 'left'},
        styleHtmlContent: true,
        iconCls: 'About',

        items:
            [
                {
                    html:[
                        '<h2 style="text-align: center"> Winebook </h2>',
                        '<p>Attribute based wine search, social wine ratings, and personal wine profile HTML5 app. </p>',
                        '<body style="background-color:LightSlateGray">',
                        '<h2 style="color:0066CC;text-align:center">Local Undergraduate Software House</h2>',
                        '<table border="1" bordercolor="#003399" style="background-color:#F0F0F0 " width="100%" cellpadding="3" cellspacing="3">',
                        '<tr>',
                        '<td><b>Name</td>',
                        '<td><b>Role</td>',
                        '<td><b>Description</td>',
                        '</tr>',
                        '<tr>',
                        '<td>Samuel Vange</td>',
                        '<td>Project Lead</td>',
                        '<td></td>',
                        '</tr>',
                        '<tr>',
                        '<td>Wu Yen Lin</td>',
                        '<td>User Interface Specialist</td>',
                        '<td>Focuses on the look and feel, and user experience.</td>',
                        '</tr>',
                        '<tr>',
                        '<td>Mandeep Singh</td>',
                        '<td>Subject Matter Expert</td>',
                        '<td>Researches wine and is involved with how the business rules are integrated into the project.</td>',
                        '</tr>',
                        '<tr>',
                        '<td>Huy Phuoc Pham </td>',
                        '<td>Software Development Lead</td>',
                        '<td>Coordinates software development.</td>',
                        '</tr>',
                        '<tr>',
                        '<td>Allen Nguyen</td>',
                        '<td>Algorithm Specialist</td>',
                        '<td>Designer of algorithms and module interfaces.</td>',
                        '</tr>',
                        '<tr>',
                        '<td>Bryan Tran</td>',
                        '<td>Database Specialist</td>',
                        '<td>Maintains database and related issues.</td>',
                        '</tr>',
                        '<tr>',
                        '<td>Leif Alan Shoquist</td>',
                        '<td>Software Architect</td>',
                        '<td>Coordinates design, selector of technologies.</td>',
                        '</tr>',
                        '<tr>',
                        '<td>Alexander Ke</td>',
                        '<td>Senior System Analyst</td>',
                        '<td>Coordinator of Use Cases, User Story, Requirements.</td>',
                        '</tr>',
                        '<tr>',
                        '<td>Khoa G Nguyen</td>',
                        '<td>Quality Assurance Lead</td>',
                        '<td>Coordinates testing phase, ensures procedures followed.</td>',
                        '</tr>',
                        '<tr>',
                        '<td>Scott Lin</td>',
                        '<td>External API Expert</td>',
                        '<td>Researches external APIs and integrates them with the project.</td>',
                        '</tr>',
                        '</table>'].join("")
                },
                {
                        xtype: 'button',
                        text:  'Close',
                        iconAlign: 'top',
                        height: '40%',
                        width: '100%',
                        flex: 3.2,
                        action:'About-close-id'
                }
            ] //end items
    }//end config

});